include: package:very_good_analysis/analysis_options.2.4.0.yaml
strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    # temporarily disabled